version: "3.9"

services:
  app-server:
    build: .
    ports:
      - "12857:12857"
    depends_on:
      - production-db
    environment:
      PM2_PUBLIC_KEY: a public key for pm2 or disable
      PM2_SECRET_KEY: a secret key for pm2 or disable
    command: yarn serve
    volumes:
        - type: bind
          source: ./logs
          target: /root/ytdpnl/logs

  production-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a password for the database admin user
      POSTGRES_DB: ytdpnl
    ports:
      - 54321:5432
    volumes:
      - production-ytdpnl:/var/lib/postgresql/data

  development-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: another password for the development database admin user
      POSTGRES_DB: ytdpnl
    ports:
      - 54322:5432
    volumes:
      - development-ytdpnl:/var/lib/postgresql/data

  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: another password for the test database admin user
      POSTGRES_DB: ytdpnl
    ports:
      - 54323:5432
    volumes:
      - test-ytdpnl:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "9180:8080"

volumes:

  production-ytdpnl:
    driver: local

  development-ytdpnl:
    driver: local

  test-ytdpnl:
    driver: local
