#!/bin/env bash
git pull
read -p "Are you sure you want to restart the container this way? The machine needs to have enough RAM available. [y/N] " -n 1 -r y
echo ""
if [[ $y =~ ^[Yy]$ ]]
then
    docker-compose up --detach --build app-server
else
    echo "Aborted!"
fi
