#!/bin/env bash
echo "Stopping running containers..."
docker-compose down
echo "Pulling latest changes from git..."
git pull
echo "Cleaning up the docker cache..."
docker-system prune
echo "Building the new container..."
docker-compose build
echo "Starting the new container..."
docker-compose up app-server
